// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Author struct {
	AuthorID uuid.UUID
	Name     string
	Bio      sql.NullString
}

type Book struct {
	BookID          uuid.UUID
	AuthorID        uuid.UUID
	PublisherID     uuid.UUID
	Title           string
	PublicationDate sql.NullTime
	Isbn            sql.NullString
	Pages           sql.NullInt32
	Genre           sql.NullString
	Description     sql.NullString
	Price           sql.NullString
	Quantity        sql.NullInt32
}

type Publisher struct {
	PublisherID uuid.UUID
	Name        string
	Address     sql.NullString
}
