// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (author_id, name, bio)
VALUES ($1, $2, $3)
    RETURNING author_id, name, bio
`

type CreateAuthorParams struct {
	AuthorID uuid.UUID
	Name     string
	Bio      sql.NullString
}

// AUTHORS
func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.AuthorID, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(&i.AuthorID, &i.Name, &i.Bio)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    book_id, author_id, publisher_id,
    title, publication_date, isbn,
    pages, genre, description,
    price, quantity
) VALUES (
             $1, $2, $3,
             $4, $5, $6,
             $7, $8, $9,
             $10, $11
         )
    RETURNING book_id, author_id, publisher_id, title, publication_date, isbn, pages, genre, description, price, quantity
`

type CreateBookParams struct {
	BookID          uuid.UUID
	AuthorID        uuid.UUID
	PublisherID     uuid.UUID
	Title           string
	PublicationDate sql.NullTime
	Isbn            sql.NullString
	Pages           sql.NullInt32
	Genre           sql.NullString
	Description     sql.NullString
	Price           sql.NullString
	Quantity        sql.NullInt32
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.BookID,
		arg.AuthorID,
		arg.PublisherID,
		arg.Title,
		arg.PublicationDate,
		arg.Isbn,
		arg.Pages,
		arg.Genre,
		arg.Description,
		arg.Price,
		arg.Quantity,
	)
	var i Book
	err := row.Scan(
		&i.BookID,
		&i.AuthorID,
		&i.PublisherID,
		&i.Title,
		&i.PublicationDate,
		&i.Isbn,
		&i.Pages,
		&i.Genre,
		&i.Description,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const createPublisher = `-- name: CreatePublisher :one
INSERT INTO publishers (publisher_id, name, address)
VALUES ($1, $2, $3)
    RETURNING publisher_id, name, address
`

type CreatePublisherParams struct {
	PublisherID uuid.UUID
	Name        string
	Address     sql.NullString
}

// PUBLISHERS
func (q *Queries) CreatePublisher(ctx context.Context, arg CreatePublisherParams) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, createPublisher, arg.PublisherID, arg.Name, arg.Address)
	var i Publisher
	err := row.Scan(&i.PublisherID, &i.Name, &i.Address)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE book_id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBook, bookID)
	return err
}

const getAllBooks = `-- name: GetAllBooks :many
SELECT book_id, author_id, publisher_id, title, publication_date, isbn, pages, genre, description, price, quantity FROM books
`

// BOOKS
func (q *Queries) GetAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.BookID,
			&i.AuthorID,
			&i.PublisherID,
			&i.Title,
			&i.PublicationDate,
			&i.Isbn,
			&i.Pages,
			&i.Genre,
			&i.Description,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT author_id, name, bio FROM authors WHERE author_id  = $1
`

func (q *Queries) GetAuthorByID(ctx context.Context, authorID uuid.UUID) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByID, authorID)
	var i Author
	err := row.Scan(&i.AuthorID, &i.Name, &i.Bio)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT book_id, author_id, publisher_id, title, publication_date, isbn, pages, genre, description, price, quantity FROM books WHERE book_id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, bookID uuid.UUID) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, bookID)
	var i Book
	err := row.Scan(
		&i.BookID,
		&i.AuthorID,
		&i.PublisherID,
		&i.Title,
		&i.PublicationDate,
		&i.Isbn,
		&i.Pages,
		&i.Genre,
		&i.Description,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const getBooksPaginated = `-- name: GetBooksPaginated :many
SELECT book_id, author_id, publisher_id, title, publication_date, isbn, pages, genre, description, price, quantity
FROM books
ORDER BY title
    LIMIT $1 OFFSET $2
`

type GetBooksPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetBooksPaginated(ctx context.Context, arg GetBooksPaginatedParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooksPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.BookID,
			&i.AuthorID,
			&i.PublisherID,
			&i.Title,
			&i.PublicationDate,
			&i.Isbn,
			&i.Pages,
			&i.Genre,
			&i.Description,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublisherByID = `-- name: GetPublisherByID :one
SELECT publisher_id, name, address FROM publishers WHERE publisher_id = $1
`

func (q *Queries) GetPublisherByID(ctx context.Context, publisherID uuid.UUID) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, getPublisherByID, publisherID)
	var i Publisher
	err := row.Scan(&i.PublisherID, &i.Name, &i.Address)
	return i, err
}

const searchBooks = `-- name: SearchBooks :many
SELECT book_id, author_id, publisher_id, title, publication_date, isbn, pages, genre, description, price, quantity
FROM books
WHERE LOWER(title) LIKE LOWER('%' || $1 || '%') OR LOWER(description) LIKE LOWER('%' || $1 || '%')
`

func (q *Queries) SearchBooks(ctx context.Context, dollar_1 sql.NullString) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, searchBooks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.BookID,
			&i.AuthorID,
			&i.PublisherID,
			&i.Title,
			&i.PublicationDate,
			&i.Isbn,
			&i.Pages,
			&i.Genre,
			&i.Description,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books SET
                 author_id = $2,
                 publisher_id = $3,
                 title = $4,
                 publication_date = $5,
                 isbn = $6,
                 pages = $7,
                 genre = $8,
                 description = $9,
                 price = $10,
                 quantity = $11
WHERE book_id = $1
    RETURNING book_id, author_id, publisher_id, title, publication_date, isbn, pages, genre, description, price, quantity
`

type UpdateBookParams struct {
	BookID          uuid.UUID
	AuthorID        uuid.UUID
	PublisherID     uuid.UUID
	Title           string
	PublicationDate sql.NullTime
	Isbn            sql.NullString
	Pages           sql.NullInt32
	Genre           sql.NullString
	Description     sql.NullString
	Price           sql.NullString
	Quantity        sql.NullInt32
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook,
		arg.BookID,
		arg.AuthorID,
		arg.PublisherID,
		arg.Title,
		arg.PublicationDate,
		arg.Isbn,
		arg.Pages,
		arg.Genre,
		arg.Description,
		arg.Price,
		arg.Quantity,
	)
	var i Book
	err := row.Scan(
		&i.BookID,
		&i.AuthorID,
		&i.PublisherID,
		&i.Title,
		&i.PublicationDate,
		&i.Isbn,
		&i.Pages,
		&i.Genre,
		&i.Description,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}
